<?php

namespace app\service;

use app\lib\attribute\DataScope;
use app\model\enums\ScopeType;
use app\repository\AttachmentRepository;
use DI\Attribute\Inject;


final class AttachmentService extends IService
{
    #[Inject]
    protected AttachmentRepository $repository;

    public function getRepository(): AttachmentRepository
    {
        return $this->repository;
    }

    #[DataScope(
        scopeType: ScopeType::CREATED_BY,
    )]
    public function page(array $params, int $page = 1, int $pageSize = 10): array
    {
        return parent::page($params, $page, $pageSize); // TODO: Change the autogenerated stub
    }
}
